CREATE OR REPLACE VIEW EXCEPTION_LOG_SIMPLE_VIEW AS
    SELECT LOG.EXCEPTION_LOG_ID     EXCEPTION_LOG_ID,
           LOG.TRIGGERING_DATE,
           TO_CHAR (LOG.TRIGGERING_DATE, 'YYYY-MM-DD HH:MI AM') SIMPLE_TRIGGERING_DATE,
           EXCEPTION.EXCEPTION_ID   EXCEPTION_ID,
           EXCEPTION.DESCRIPTION    DESCRIPTION,
           LOG.STACK_TRACE          STACK_TRACE,
           LOG.ADDITIONAL_INFO      ADDITIONAL_INFO
    FROM CTI_EXCEPTION_LOG   LOG
    INNER JOIN CTI_EXCEPTION       EXCEPTION ON LOG.EXCEPTION_ID = EXCEPTION.EXCEPTION_ID
    ORDER BY LOG.EXCEPTION_LOG_ID DESC;