create or replace PACKAGE PKG_EXPOSED_SERVICES_FACADE AS
    PROCEDURE ESTUDIANTE (
        P_CODIGO_ESTUDIANTE VARCHAR2
    );
    
    PROCEDURE GET_PLANES (
        P_CODIGO_ESTUDIANTE VARCHAR2
    );
    
    PROCEDURE ACTUALIZAR_PLAN_POSTGRADO (
        P_CODIGO_ESTUDIANTE VARCHAR2,
        P_PLAN_ESTUDIO VARCHAR2
    );
    
    PROCEDURE ESTUDIANTE_CODIGO_CONTRARIO (
        P_CODIGO_ESTUDIANTE VARCHAR2
    );

    PROCEDURE GET_PREMATRICULA_ESTUDIANTE (
        P_CODIGO_ESTUDIANTE VARCHAR2
    );

    PROCEDURE GET_GENERALIDADES (
        P_CODIGO_ESTUDIANTE VARCHAR2
    );

    PROCEDURE GET_HORARIO_DOCENTE (
        P_DOCUMENTO VARCHAR2
    );
     PROCEDURE GET_PENDIENTES (
        P_CODIGO_ESTUDIANTE VARCHAR2
    );
END PKG_EXPOSED_SERVICES_FACADE;