CREATE OR REPLACE PACKAGE PKG_JSON_RESPONSE IS
    PROCEDURE TEST_JSON_RESPONSE;

    PROCEDURE PRINT_SUCCESSFUL (
        P_TEXT VARCHAR2
    );

    PROCEDURE PRINT_SUCCESSFUL (
        P_JSON JSON
    );

    PROCEDURE PRINT_SUCCESSFUL (
        P_JSON_LIST JSON_LIST
    );

    PROCEDURE PRINT_FAILURE_OR_EXCEPTION;

END;
/

CREATE OR REPLACE PACKAGE BODY PKG_JSON_RESPONSE IS

    PROCEDURE TEST_JSON_RESPONSE IS
        V_JSON        JSON DEFAULT JSON ();
        V_JSON_LIST   JSON_LIST DEFAULT JSON_LIST ();
        V_NUMBER      NUMBER;
    BEGIN
        V_NUMBER      := 1 / 0;     
        
        /* IMPRIMIENDO VARCHAR2.*/
        PRINT_SUCCESSFUL ('PRUEBITA');
        
        /* IMPRIMIENDO JSON.*/
        JSON.PUT (V_JSON, 'status', 'ok');
        PRINT_SUCCESSFUL (V_JSON);
        
        /* IMPRIMIENDO JSON_LIST.*/
        V_JSON_LIST   := JSON_LIST ();
        V_JSON        := JSON ();
        JSON.PUT (V_JSON, 'property', 'value');
        JSON_LIST.APPEND (V_JSON_LIST, V_JSON.TO_JSON_VALUE);
        V_JSON        := JSON ();
        JSON.PUT (V_JSON, 'property', 'value');
        JSON_LIST.APPEND (V_JSON_LIST, V_JSON.TO_JSON_VALUE);
        V_JSON        := JSON ();
        JSON.PUT (V_JSON, 'property', 'value');
        JSON_LIST.APPEND (V_JSON_LIST, V_JSON.TO_JSON_VALUE);
        PRINT_SUCCESSFUL (V_JSON_LIST);
    EXCEPTION
        WHEN OTHERS THEN
            PKG_JSON_RESPONSE.PRINT_FAILURE_OR_EXCEPTION;
    END;

    PROCEDURE PRINT_SUCCESSFUL (
        P_TEXT VARCHAR2
    ) IS
        V_JSON JSON DEFAULT JSON ();
    BEGIN
        POSTGRADO.PKG_HTML.CORSHEADERS;
        JSON.PUT (V_JSON, 'status', 'ok');
        JSON.PUT (V_JSON, 'response', P_TEXT);
        JSON.HTP (V_JSON);
    END;

    PROCEDURE PRINT_SUCCESSFUL (
        P_JSON JSON
    ) IS
        V_JSON JSON DEFAULT JSON ();
    BEGIN
        POSTGRADO.PKG_HTML.CORSHEADERS;
        JSON.PUT (V_JSON, 'status', 'ok');
        JSON.PUT (V_JSON, 'response', P_JSON);
        JSON.HTP (V_JSON);
    END;

    PROCEDURE PRINT_SUCCESSFUL (
        P_JSON_LIST JSON_LIST
    ) IS
        V_JSON JSON DEFAULT JSON ();
    BEGIN
        POSTGRADO.PKG_HTML.CORSHEADERS;
        JSON.PUT (V_JSON, 'status', 'ok');
        JSON.PUT (V_JSON, 'response', P_JSON_LIST);
        JSON.HTP (V_JSON);
    END;

    PROCEDURE PRINT_FAILURE_OR_EXCEPTION IS
        V_JSON            JSON := JSON ();
        V_EXCEPTION_LOG   CTI_EXCEPTION_LOG%ROWTYPE;
        V_EXCEPTION       CTI_EXCEPTION%ROWTYPE;
    BEGIN
        POSTGRADO.PKG_HTML.CORSHEADERS;
        V_EXCEPTION_LOG   := PKG_EXCEPTION.GET_EXCEPTION_LOG (PKG_EXCEPTION.LOG_EXCEPTION ());
        V_EXCEPTION       := PKG_EXCEPTION.GET_EXCEPTION (V_EXCEPTION_LOG.EXCEPTION_ID);
        JSON.PUT (V_JSON, 'status', 'fail');
        JSON.PUT (V_JSON, 'error', V_EXCEPTION_LOG.EXCEPTION_LOG_ID);
        IF (V_EXCEPTION_LOG.ADDITIONAL_INFO LIKE '%' ||
        V_EXCEPTION.DESCRIPTION || '%') THEN
            JSON.PUT (V_JSON, 'descripcion', V_EXCEPTION.DESCRIPTION);
        ELSE
            JSON.PUT (V_JSON, 'descripcion', V_EXCEPTION.DESCRIPTION ||
            ': ' ||
            V_EXCEPTION_LOG.ADDITIONAL_INFO);
        END IF;

        JSON.HTP (V_JSON);
    END;

END;
/

CREATE OR REPLACE PACKAGE PKG_EXCEPTION IS
    PROCEDURE TEST_EXCEPTION (
        P_EXCEPTION_ID CTI_EXCEPTION.EXCEPTION_ID%TYPE
    );

    PROCEDURE RAISE_EXCEPTION (
        P_EXCEPTION_ID CTI_EXCEPTION.EXCEPTION_ID%TYPE
    );

    PROCEDURE RAISE_EXCEPTION_WITH_INFO (
        P_EXCEPTION_ID   CTI_EXCEPTION.EXCEPTION_ID%TYPE,
        P_INFO           VARCHAR2
    );

    FUNCTION GET_EXCEPTION (
        P_EXCEPTION_ID CTI_EXCEPTION.EXCEPTION_ID%TYPE
    ) RETURN CTI_EXCEPTION%ROWTYPE;

    FUNCTION GET_EXCEPTION_LOG (
        P_EXCEPTION_LOG_ID CTI_EXCEPTION_LOG.EXCEPTION_LOG_ID%TYPE
    ) RETURN CTI_EXCEPTION_LOG%ROWTYPE;

    PROCEDURE LOG_EXCEPTION;

    FUNCTION LOG_EXCEPTION RETURN CTI_EXCEPTION_LOG.EXCEPTION_LOG_ID%TYPE;

    FUNCTION INSERT_EXCEPTION (
        P_EXCEPTION CTI_EXCEPTION%ROWTYPE
    ) RETURN CTI_EXCEPTION_LOG.EXCEPTION_LOG_ID%TYPE;

END;
/

CREATE OR REPLACE PACKAGE BODY PKG_EXCEPTION IS

    V_UNDEFINED_EXCEPTION         CTI_EXCEPTION.EXCEPTION_ID%TYPE DEFAULT '-20000';
    V_EXCEPTION_LOG_NOT_FOUNDED   CTI_EXCEPTION.EXCEPTION_ID%TYPE DEFAULT '-20001';
    
    /*
        -----------------------------------------------------------------------------
        PROCEDIMIENTO PARA PRUEBA DE EXCEPCIONES POR PETICION WEB.
        @param P_EXCEPTION_ID CTI_EXCEPTION.EXCEPTION_ID%TYPE
        -----------------------------------------------------------------------------
        */

    PROCEDURE TEST_EXCEPTION (
        P_EXCEPTION_ID CTI_EXCEPTION.EXCEPTION_ID%TYPE
    ) IS
        V_NUMBER NUMBER;
    BEGIN
        /*RAISE_EXCEPTION_WITH_INFO (P_EXCEPTION_ID, 'TEST');
        V_NUMBER := 1 / 0;*/
        RAISE_EXCEPTION (P_EXCEPTION_ID);
    EXCEPTION
        WHEN OTHERS THEN
            PKG_JSON_RESPONSE.PRINT_FAILURE_OR_EXCEPTION ();
    END;
    
    /*
        -----------------------------------------------------------------------------
        PROCEDIMIENTO PARA LANZAMIENTO DE EXCEPTION.
        @param P_EXCEPTION_ID CTI_EXCEPTION.EXCEPTION_ID%TYPE
        -----------------------------------------------------------------------------
        */

    PROCEDURE RAISE_EXCEPTION (
        P_EXCEPTION_ID CTI_EXCEPTION.EXCEPTION_ID%TYPE
    ) IS
        V_EXCEPTION CTI_EXCEPTION%ROWTYPE;
    BEGIN
        V_EXCEPTION := GET_EXCEPTION (P_EXCEPTION_ID);
        RAISE_APPLICATION_ERROR (V_EXCEPTION.EXCEPTION_ID, V_EXCEPTION.DESCRIPTION);
    END;
    
    /*    
        -----------------------------------------------------------------------------
        @param P_EXCEPTION_ID CTI_EXCEPTION.EXCEPTION_ID%TYPE
        @param P_INFO VARCHAR2
        -----------------------------------------------------------------------------
        */

    PROCEDURE RAISE_EXCEPTION_WITH_INFO (
        P_EXCEPTION_ID   CTI_EXCEPTION.EXCEPTION_ID%TYPE,
        P_INFO           VARCHAR2
    ) IS
        V_EXCEPTION CTI_EXCEPTION%ROWTYPE;
    BEGIN
        V_EXCEPTION := GET_EXCEPTION (P_EXCEPTION_ID);
        RAISE_APPLICATION_ERROR (V_EXCEPTION.EXCEPTION_ID, P_INFO);
    END;
    /*
        -----------------------------------------------------------------------------
        OBTIENE REGISTRO DE CTI_EXCEPTION.
        @param P_EXCEPTION_ID CTI_EXCEPTION.EXCEPTION_ID%TYPE
        @return 
        -----------------------------------------------------------------------------
        */

    FUNCTION GET_EXCEPTION (
        P_EXCEPTION_ID CTI_EXCEPTION.EXCEPTION_ID%TYPE
    ) RETURN CTI_EXCEPTION%ROWTYPE IS
        V_EXCEPTION CTI_EXCEPTION%ROWTYPE;
    BEGIN
        SELECT CTI_EXCEPTION.EXCEPTION_ID,
               CTI_EXCEPTION.DESCRIPTION
        INTO V_EXCEPTION
        FROM CTI_EXCEPTION
        WHERE CTI_EXCEPTION.EXCEPTION_ID = P_EXCEPTION_ID;

        RETURN V_EXCEPTION;
    EXCEPTION
        WHEN OTHERS THEN
            V_EXCEPTION := GET_EXCEPTION (V_UNDEFINED_EXCEPTION);
            RETURN V_EXCEPTION;
    END;

    /*
        -----------------------------------------------------------------------------
        OBTIENE REGISTRO DE CTI_EXCEPTION_LOG.
        @param P_EXCEPTION_LOG_ID CTI_EXCEPTION_LOG.EXCEPTION_LOG_ID%TYPE
        @return 
        -----------------------------------------------------------------------------
        */

    FUNCTION GET_EXCEPTION_LOG (
        P_EXCEPTION_LOG_ID CTI_EXCEPTION_LOG.EXCEPTION_LOG_ID%TYPE
    ) RETURN CTI_EXCEPTION_LOG%ROWTYPE IS
        V_EXCEPTION_LOG CTI_EXCEPTION_LOG%ROWTYPE;
    BEGIN
        SELECT EXCEPTION_LOG_ID,
               TRIGGERING_DATE,
               EXCEPTION_ID,
               STACK_TRACE,
               ADDITIONAL_INFO
        INTO V_EXCEPTION_LOG
        FROM CTI_EXCEPTION_LOG
        WHERE CTI_EXCEPTION_LOG.EXCEPTION_LOG_ID = P_EXCEPTION_LOG_ID;

        RETURN V_EXCEPTION_LOG;
    EXCEPTION
        WHEN OTHERS THEN
            RAISE_EXCEPTION (V_EXCEPTION_LOG_NOT_FOUNDED);
            RETURN NULL;
    END;
    
    /*
        -----------------------------------------------------------------------------
        IMPRIME, EN HTML (JSON), EL ID DEL LOG DE EXCEPCION, CON SU RESPECTIVA 
        DESCRIPCION.
        @param P_EXCEPTION_LOG_ID CTI_EXCEPTION_LOG.EXCEPTION_LOG_ID%TYPE
        -----------------------------------------------------------------------------
        */

    PROCEDURE PRINT_JSON_EXCEPTION (
        P_EXCEPTION_LOG_ID CTI_EXCEPTION_LOG.EXCEPTION_LOG_ID%TYPE
    ) IS
        V_JSON            JSON := JSON ();
        V_EXCEPTION_LOG   CTI_EXCEPTION_LOG%ROWTYPE;
        V_EXCEPTION       CTI_EXCEPTION%ROWTYPE;
    BEGIN
        POSTGRADO.PKG_HTML.CORSHEADERS;
        V_EXCEPTION_LOG   := GET_EXCEPTION_LOG (P_EXCEPTION_LOG_ID);
        V_EXCEPTION       := GET_EXCEPTION (V_EXCEPTION_LOG.EXCEPTION_ID);
        JSON.PUT (V_JSON, 'status', 'fail');
        JSON.PUT (V_JSON, 'error', V_EXCEPTION_LOG.EXCEPTION_LOG_ID);
        JSON.PUT (V_JSON, 'descripcion', V_EXCEPTION.DESCRIPTION);
        JSON.HTP (V_JSON);
    END;

    /*
        -----------------------------------------------------------------------------
        AGREGA EXCEPCION AL LOG (CTI_EXCEPTION_LOG).
        @return 
        -----------------------------------------------------------------------------
        */

    PROCEDURE LOG_EXCEPTION IS
        V_EXCEPTION_LOG_ID CTI_EXCEPTION_LOG.EXCEPTION_LOG_ID%TYPE DEFAULT NULL;
    BEGIN
        V_EXCEPTION_LOG_ID := PKG_EXCEPTION.LOG_EXCEPTION ();
    END;

    /*
        -----------------------------------------------------------------------------
        AGREGA EXCEPCION AL LOG (CTI_EXCEPTION_LOG).
        @return 
        -----------------------------------------------------------------------------
        */

    FUNCTION LOG_EXCEPTION RETURN CTI_EXCEPTION_LOG.EXCEPTION_LOG_ID%TYPE IS
        V_EXCEPTION          CTI_EXCEPTION%ROWTYPE;
        V_EXCEPTION_LOG_ID   CTI_EXCEPTION_LOG.EXCEPTION_LOG_ID%TYPE DEFAULT NULL;
    BEGIN
        V_EXCEPTION := GET_EXCEPTION (SQLCODE);
        RETURN INSERT_EXCEPTION (V_EXCEPTION);
    END;
            
    /*
        -----------------------------------------------------------------------------
        INSERTA REGISTRO EN CTI_EXCEPTION_LOG PARA EXCEPCIONES DEL SISTEMA.
        @param P_EXCEPTION_LOG_ID CTI_EXCEPTION_LOG.EXCEPTION_LOG_ID%TYPE
        @param P_SQLERRM VARCHAR2
        -----------------------------------------------------------------------------
        */

    FUNCTION INSERT_EXCEPTION (
        P_EXCEPTION CTI_EXCEPTION%ROWTYPE
    ) RETURN CTI_EXCEPTION_LOG.EXCEPTION_LOG_ID%TYPE IS
        V_SQLERRM CTI_EXCEPTION_LOG.ADDITIONAL_INFO%TYPE DEFAULT SQLERRM;
    BEGIN
        INSERT INTO CTI_EXCEPTION_LOG (
            TRIGGERING_DATE,
            EXCEPTION_ID,
            STACK_TRACE,
            ADDITIONAL_INFO
        ) VALUES (
            SYSDATE,
            P_EXCEPTION.EXCEPTION_ID,
            DBMS_UTILITY.FORMAT_ERROR_BACKTRACE,
            V_SQLERRM
        );

        RETURN CTI_EXCEPTION_LOG_SEQ.CURRVAL;
    END;

END;
/

DROP SEQUENCE CTI_EXCEPTION_LOG_SEQ;

DROP TRIGGER CTI_EXCEPTION_LOG_TRG;

DROP TABLE CTI_EXCEPTION_LOG;

DROP TRIGGER CTI_EXCEPTION_TRG;

DROP TABLE CTI_EXCEPTION;

/* CREACION DE TABLA.*/

CREATE TABLE CTI_EXCEPTION (
    EXCEPTION_ID   NUMBER PRIMARY KEY,
    DESCRIPTION    VARCHAR2 (2000),
    CONSTRAINT CTI_EXCEPTION_ID CHECK (EXCEPTION_ID <= -20000)
);
/

ALTER TABLE CTI_EXCEPTION ADD CONSTRAINT CTI_EXCEPTION_ID CHECK (EXCEPTION_ID <= -20000);
/

/* CREACION DE SECUENCIA.*/

CREATE SEQUENCE CTI_EXCEPTION_LOG_SEQ START WITH 1;
/* CREACION DE TABLA.*/

CREATE TABLE CTI_EXCEPTION_LOG (
    EXCEPTION_LOG_ID   NUMBER PRIMARY KEY NOT NULL,
    TRIGGERING_DATE    DATE NOT NULL,
    EXCEPTION_ID       NUMBER NOT NULL,
    STACK_TRACE        VARCHAR (4000) NOT NULL,
    ADDITIONAL_INFO    VARCHAR2 (4000),
    CONSTRAINT CTI_EXC_LOG_EXC FOREIGN KEY (EXCEPTION_ID)
        REFERENCES CTI_EXCEPTION (EXCEPTION_ID)
);
/* CREACION DE TRIGGER.*/

CREATE TRIGGER CTI_EXCEPTION_LOG_TRG BEFORE
    INSERT ON CTI_EXCEPTION_LOG
    FOR EACH ROW
BEGIN
    SELECT CTI_EXCEPTION_LOG_SEQ.NEXTVAL
    INTO :NEW.EXCEPTION_LOG_ID
    FROM DUAL;

END;
/

GRANT EXECUTE ON PKG_JSON_RESPONSE TO ADMISIONES;
GRANT EXECUTE ON PKG_JSON_RESPONSE TO CACTUALPRE;
GRANT EXECUTE ON PKG_JSON_RESPONSE TO POSTGRADO;
GRANT EXECUTE ON PKG_JSON_RESPONSE TO CACTUALPOS;
GRANT EXECUTE ON PKG_JSON_RESPONSE TO YOPAL;
GRANT EXECUTE ON PKG_JSON_RESPONSE TO CACTUALYOP;
GRANT EXECUTE ON PKG_JSON_RESPONSE TO DESARROLLOSPRE;
GRANT EXECUTE ON PKG_JSON_RESPONSE TO DESARROLLOSPOS;
GRANT EXECUTE ON PKG_EXCEPTION TO ADMISIONES;
GRANT EXECUTE ON PKG_EXCEPTION TO CACTUALPRE;
GRANT EXECUTE ON PKG_EXCEPTION TO POSTGRADO;
GRANT EXECUTE ON PKG_EXCEPTION TO CACTUALPOS;
GRANT EXECUTE ON PKG_EXCEPTION TO YOPAL;
GRANT EXECUTE ON PKG_EXCEPTION TO CACTUALYOP;
GRANT EXECUTE ON PKG_EXCEPTION TO DESARROLLOSPRE;
GRANT EXECUTE ON PKG_EXCEPTION TO DESARROLLOSPOS;

INSERT INTO CTI_EXCEPTION (EXCEPTION_ID, DESCRIPTION) VALUES ('-20000', 'UNDEFINED EXCEPTION');

INSERT INTO CTI_EXCEPTION (EXCEPTION_ID, DESCRIPTION) VALUES ('-20001', 'No existe auditoria de excepciones para el registro indicado');

INSERT INTO CTI_EXCEPTION (EXCEPTION_ID, DESCRIPTION) VALUES ('-20002', 'El estudiante no existe');

INSERT INTO CTI_EXCEPTION (EXCEPTION_ID, DESCRIPTION) VALUES ('-20003', 'El programa no existe');

INSERT INTO CTI_EXCEPTION (EXCEPTION_ID, DESCRIPTION) VALUES ('-20004', 'El estudiante ya está inscrito');

INSERT INTO CTI_EXCEPTION (EXCEPTION_ID, DESCRIPTION) VALUES ('-20005', 'El campo no puede ser nulo o vacío');

INSERT INTO CTI_EXCEPTION (EXCEPTION_ID, DESCRIPTION) VALUES ('-20006', 'Error en validación de campo');

INSERT INTO CTI_EXCEPTION (EXCEPTION_ID, DESCRIPTION) VALUES ('-20007', 'La tabla no contiene la columna descrita');

INSERT INTO CTI_EXCEPTION (EXCEPTION_ID, DESCRIPTION) VALUES ('-20008', 'El valor ingresado no es valido');

SELECT *
FROM CTI_EXCEPTION;


SELECT LOG.EXCEPTION_LOG_ID     EXCEPTION_LOG_ID,
       TO_CHAR (LOG.TRIGGERING_DATE, 'YYYY-MM-DD HH:MI:SS')     TRIGGERING_DATE,
       EXCEPTION.EXCEPTION_ID   EXCEPTION_ID,
       EXCEPTION.DESCRIPTION    DESCRIPTION,
       LOG.STACK_TRACE          STACK_TRACE,
       LOG.ADDITIONAL_INFO      ADDITIONAL_INFO
FROM CTI_EXCEPTION_LOG   LOG
INNER JOIN CTI_EXCEPTION       EXCEPTION ON LOG.EXCEPTION_ID = EXCEPTION.EXCEPTION_ID
ORDER BY LOG.EXCEPTION_LOG_ID DESC;