CREATE OR REPLACE PACKAGE PKG_DESCUENTOS AS
    FUNCTION NULL_FUNCTION (
        P_CODIGO_ESTUDIANTE VARCHAR2
    ) RETURN NUMBER;
    
    FUNCTION ES_EGRESADO_NUEVO (
        P_CODIGO_ESTUDIANTE VARCHAR2
    ) RETURN NUMBER;

    FUNCTION ES_EGRESADO_ANTIGUO (
        P_CODIGO_ESTUDIANTE VARCHAR2
    ) RETURN NUMBER;
    
    FUNCTION ES_ULTIMA_MATERIA (
        P_CODIGO_ESTUDIANTE VARCHAR2
    ) RETURN NUMBER;
END PKG_DESCUENTOS;