CREATE OR REPLACE PROCEDURE UPDATE_SEMESTRE_SUP_INF (
    P_CODIGO_ESTUDIANTE VARCHAR2
) IS

    V_ANIO                VARCHAR2 (4);
    V_CICLO               VARCHAR2 (2);
    V_ESQUEMA             VARCHAR2 (32);
    V_SEMESTRE_INFERIOR   VARCHAR2 (2) DEFAULT 0;
    V_SEMESTRE_SUPERIOR   VARCHAR2 (2) DEFAULT 0;
BEGIN
    ADMISIONES.PKG_UTILS.GETANIOCICLOESQUEMA ('2', V_ANIO, V_CICLO, V_ESQUEMA);
    EXECUTE IMMEDIATE q'!
            SELECT MIN (M.SEMESTRE),
                   MAX (M.SEMESTRE)
            FROM !' || V_ESQUEMA || q'!.B_PREMATRICULA   BP,
                 POSTGRADO.A_MATERIAS       M
            WHERE BP.CODIGO_ESTUDIANTE = :codigo
                  AND BP.FACULTAD = M.CODIGO_FACULTAD
                      AND BP.JORNADA_FACULTAD = M.JORNADA_FACULTAD
                          AND BP.MATERIA_PLAN = M.CODIGO
                              AND BP.INDICADOR_REGLAMENTO IS NULL
        !'
    INTO
        V_SEMESTRE_INFERIOR,
        V_SEMESTRE_SUPERIOR
        USING P_CODIGO_ESTUDIANTE;
    EXECUTE IMMEDIATE Q'!
            UPDATE !' || V_ESQUEMA || q'!.B_ESTUDIANTES BE
            SET BE.SEMESTRE_INFERIOR = :semestreInferior,
                BE.SEMESTRE_SUPERIOR = :semestreSuperior
            WHERE BE.CODIGO = :codigo
        !'
        USING V_SEMESTRE_INFERIOR, V_SEMESTRE_SUPERIOR, P_CODIGO_ESTUDIANTE;
/*EXCEPTION
    WHEN OTHERS THEN
        ADMISIONES.PKG_EXCEPTION.LOG_EXCEPTION ();*/
END;
/