
CREATE OR REPLACE FUNCTION CC_ENCRYPT (
    P_VALUE VARCHAR2
) RETURN VARCHAR2
IS
BEGIN
    RETURN XAMPLECRIPTO(P_VALUE,'3764613438353137');
END;
/
CREATE OR REPLACE FUNCTION CC_DECRYPT (
    P_VALUE VARCHAR2
) RETURN VARCHAR2
IS
    V_DECRYPTED VARCHAR2(4000);
BEGIN
  DBMS_OBFUSCATION_TOOLKIT.DESDECRYPT(INPUT_STRING => UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW(P_VALUE)),
                                      KEY_STRING => UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('3764613438353137')), 
                                      DECRYPTED_STRING => V_DECRYPTED);
  RETURN TRIM(V_DECRYPTED);
END;
/