CREATE FUNCTION ESTA_MATRICULADO (
    P_INDICADOR_PAGO VARCHAR2
) RETURN NUMBER IS
BEGIN
    IF (P_INDICADOR_PAGO IN (
        'P',
        'V',
        'W'
    )) THEN
        RETURN 1;
    ELSE
        RETURN 0;
    END IF;
END;
/

GRANT EXECUTE ON ESTA_MATRICULADO TO CACTUALPRE;
GRANT EXECUTE ON ESTA_MATRICULADO TO CACTUALPOS;
GRANT EXECUTE ON ESTA_MATRICULADO TO DESARROLLOSPRE;
GRANT EXECUTE ON ESTA_MATRICULADO TO DESARROLLOSPOS;
GRANT EXECUTE ON ESTA_MATRICULADO TO POSTGRADO;

-- REPLACE: INDICADOR_PAGO IN ('P', 'V') -> ADMISIONES.ESTA_MATRICULADO(INDICADOR_PAGO) = '1'


SELECT * FROM B_ESTUDIANTES WHERE ADMISIONES.ESTA_MATRICULADO(INDICADOR_PAGO) = '1';
