CREATE OR REPLACE FUNCTION FALTA_ENCUESTA_SATISFACCION (P_CODIGO_ESTUDIANTE VARCHAR2) RETURN NUMBER IS
    V_RETURNABLE NUMBER;
BEGIN
    SELECT CASE
        WHEN NUM_REGISTROS = '1' THEN
            '0'
        ELSE
            '1'
    END
    INTO V_RETURNABLE
    FROM (SELECT COUNT (*) NUM_REGISTROS
          FROM ADMISIONES.A_SATISFACCION_ESTUDIANTES
          WHERE A_SATISFACCION_ESTUDIANTES.CODIGO = P_CODIGO_ESTUDIANTE
          UNION
          SELECT COUNT (*) NUM_REGISTROS
          FROM POSTGRADO.A_SATISFACCION_ESTUDIANTES
          WHERE A_SATISFACCION_ESTUDIANTES.CODIGO = P_CODIGO_ESTUDIANTE
         ) A;

    RETURN V_RETURNABLE;
END;
/