CREATE OR REPLACE FUNCTION NUMERO_ENCUESTAS_PENDIENTES (
    P_CODIGO_ESTUDIANTE VARCHAR
) RETURN NUMBER IS
    V_RETURNABLE NUMBER;
BEGIN
    SELECT COUNT (*)
    INTO V_RETURNABLE
    FROM SIE.SIE_VW_ENCU_AUTO_PRE_SALL_ESTU@UVIRTUAL.LASALLE.EDU.CO
    WHERE CODIGO = P_CODIGO_ESTUDIANTE
          AND CONTESTO = 'NO';

    RETURN V_RETURNABLE;
END;
/

CREATE OR REPLACE FUNCTION NUMERO_EVAL_DOCENTE_PENDIENTES (
    P_CODIGO_ESTUDIANTE VARCHAR
) RETURN NUMBER IS
    V_RETURNABLE NUMBER;
BEGIN
    SELECT COUNT (*)
    INTO V_RETURNABLE
    FROM (SELECT SIIS.VALIDAR_CONSULTA_ESTUDIANTE@UVIRTUAL.LASALLE.EDU.CO (P_CODIGO_ESTUDIANTE) A
          FROM DUAL T
         )
    WHERE A != 'S' AND ;

    RETURN V_RETURNABLE;
END;
/