create or replace PACKAGE PKG_PREMATRICULA_AUX
AS
	PROCEDURE GRUPO_JSON_OBJECT(
		P_JSON_OBJECT OUT JSON,
		P_CONSECUTIVO IN INTEGER,
		P_ELIMINABLE  IN INTEGER,
		P_YOPAL       IN INTEGER DEFAULT 0);
        
    FUNCTION GET_HORARIO_PREGRADO(
            P_CONSECUTIVO NUMBER
        ) RETURN JSON_LIST;
        
    FUNCTION GET_HORARIO_POSTGRADO(
            P_CONSECUTIVO NUMBER
        ) RETURN JSON_LIST;
        
	PROCEDURE PREMATRICULA(
		P_CODIGO   		VARCHAR2,
		P_ANIO     		VARCHAR2,
		P_CICLO    		VARCHAR2,
		P_TIPO     		NUMBER DEFAULT 0,
		P_MOSTRAR_NOTAS NUMBER DEFAULT 0);
END PKG_PREMATRICULA_AUX;