CREATE OR REPLACE TRIGGER SEGUROCUPOS BEFORE
    INSERT ON B_PREMATRICULA
    FOR EACH ROW
DECLARE
    V_ESQUEMA_GRUPO NUMBER;    
    V_PREGRADO NUMBER DEFAULT '1';
    V_POSTGRADO NUMBER DEFAULT '2';
    V_CONSECUTIVO NUMBER;
    V_CUPO_UTILIZADO A_HORARIO_HORIZONTAL.CUPO_UTILIZADO%TYPE DEFAULT NULL;
    V_CUPO A_HORARIO_HORIZONTAL.CUPO%TYPE DEFAULT NULL;
    V_FACUR A_HORARIO_HORIZONTAL.CODIGO_FACULTAD%TYPE DEFAULT NULL;
BEGIN
    SELECT UNIQUE ESQUEMA,
                  CONSECUTIVO
    INTO          V_ESQUEMA_GRUPO,
                  V_CONSECUTIVO
    FROM          (SELECT V_PREGRADO ESQUEMA,
                          CONSECUTIVO
                   FROM   ADMISIONES.A_HORARIO_HORIZONTAL
                   WHERE      CODIGO_FACULTAD = :NEW.FACULTAD_CURSAR 
                          AND CODIGO_MATERIA = :NEW.MATERIA_CURSAR 
                          AND TO_NUMBER (GRUPO_MATERIA) = :NEW.GRUPO
                   UNION
                   SELECT V_POSTGRADO,
                          CONSECUTIVO
                   FROM   POSTGRADO.A_HORARIO_HORIZONTAL
                   WHERE      CODIGO_FACULTAD = :NEW.FACULTAD_CURSAR 
                          AND CODIGO_MATERIA = :NEW.MATERIA_CURSAR 
                          AND TO_NUMBER (GRUPO_MATERIA) = :NEW.GRUPO) B;    
    
    IF (V_ESQUEMA_GRUPO = V_PREGRADO AND :NEW.FACULTAD_CURSAR < '71') THEN
        SELECT HH.CODIGO_FACULTAD
        INTO   V_FACUR
        FROM   ADMISIONES.A_HORARIO_HORIZONTAL HH
        WHERE  CONSECUTIVO = V_CONSECUTIVO;     
        IF (V_FACUR < '71') THEN
            SELECT HH.CUPO_UTILIZADO, 
                   HH.CUPO
            INTO   V_CUPO_UTILIZADO, 
                   V_CUPO
            FROM   ADMISIONES.A_HORARIO_HORIZONTAL HH
            WHERE  CONSECUTIVO = V_CONSECUTIVO;  
            IF (V_CUPO_UTILIZADO >= V_CUPO) THEN
                RAISE_APPLICATION_ERROR (-20001, 'No hay cupo disponible en la materia.');
            END IF;
        END IF;
    ELSIF(V_ESQUEMA_GRUPO = V_POSTGRADO) THEN
        SELECT HH.CUPO_UTILIZADO, 
               HH.CUPO
        INTO   V_CUPO_UTILIZADO, 
               V_CUPO
        FROM   POSTGRADO.A_HORARIO_HORIZONTAL HH
        WHERE  CONSECUTIVO = V_CONSECUTIVO;  
        IF (V_CUPO_UTILIZADO >= V_CUPO) THEN
            RAISE_APPLICATION_ERROR (-20002, 'No hay cupo disponible en la materia.');
        END IF;
    END IF;
END SEGUROCUPOS;